driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: freebsd-9.3
- name: freebsd-9.3-i386
- name: freebsd-10.2

suites:
- name: portsnap
  run_list: freebsd::portsnap

- name: pkgng
  run_list: freebsd::pkgng
