AllCops:
  Exclude:
    - Guardfile
    - vendor/**/*

AlignParameters:
  Enabled: false
ClassAndModuleChildren:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
SingleSpaceBeforeFirstArg:
  Enabled: false
